coverage:
  status:
    project:
      default:
        target: auto
        base: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        base: auto
        threshold: 1%
        informational: true

ignore:
  - "tests/"
  - "addons/gdUnit4/"
  - ".godot/"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
